FORMAT: 1A

# taigi-neologism

## GET /列表/外語請教條
+ Response 200 (application/json)

        {
          "列表": [
            {
              "外語請教條項目編號": "47765",
              "外語語言": "華語",
              "種類": "字詞",
              "語言腔口": "閩南語",
              "外語資料": "鬱歲"
            },
          ]
        }

## GET /揣/外語請教條?關鍵字={keyword}
+ Response 200 (application/json)

        {
          "其他建議": [
            {
              "外語請教條項目編號": "37998",
              "外語語言": "華語",
              "種類": "字詞",
              "語言腔口": "閩南語",
              "外語資料": "漂漂亮亮"
            },
            {
              "外語請教條項目編號": "34267",
              "外語語言": "華語",
              "種類": "字詞",
              "語言腔口": "閩南語",
              "外語資料": "愛漂亮"
            }
          ],
          "資料": [
            {
              "外語請教條項目編號": "37991",
              "外語語言": "華語",
              "種類": "字詞",
              "語言腔口": "閩南語",
              "外語資料": "漂亮"
            }
          ]
        }

## GET /資料內容?平臺項目編號={number}
+ Response 200 (application/json)

        {
          "屬性內容": {},
          "外語請教條項目編號": "47765",
          "外語語言": "華語",
          "來源": 2,
          "種類": "字詞",
          "新詞文本": [
            {
              "文本資料": "鬱歲",
              "屬性內容": {
                "音標": "ut-huè/ut-hè"
              },
              "來源": 2,
              "新詞文本項目編號": "47766",
              "收錄者": 1,
              "收錄時間": "2015-04-13 22:04:54"
            }
          ],
          "收錄者": 1,
          "新詞影音": [],
          "語言腔口": "閩南語",
          "外語資料": "鬱歲",
          "收錄時間": "2015-04-13 22:04:54"
        }

## GET /看csrf
+ Response 200 (application/json)

        {
          "csrftoken": "YNojHNaWlKN40iV9O0iyNBfZFkRw3laW"
        }
